import sqlite3

conexao = sqlite3.connect('banco_de_dados/banco_agro.db')
cursor = conexao.cursor()

cursor.execute('''
CREATE TABLE analises_solo (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    fosforo_mehlich REAL,
    obs_fosforo_mehlich TEXT,
    fosforo_remanescente REAL,
    obs_fosforo_remanescente TEXT,
    fosforo_resina REAL,
    obs_fosforo_resina TEXT,
    potassio REAL,
    obs_potassio TEXT,
    enxofre REAL,
    obs_enxofre TEXT,
    calcio REAL,
    obs_calcio TEXT,
    magnesio REAL,
    obs_magnesio TEXT,
    aluminio REAL,
    obs_aluminio TEXT,
    hal REAL,
    obs_hal TEXT,
    ph_h2o REAL,
    obs_ph_h2o TEXT,
    ph_cacl2 REAL,
    obs_ph_cacl2 TEXT,
    ph_smp REAL,
    obs_ph_smp TEXT,
    materia_organica REAL,
    obs_materia_organica TEXT,
    ferro REAL,
    obs_ferro TEXT,
    zinco REAL,
    obs_zinco TEXT,
    cobre REAL,
    obs_cobre TEXT,
    manganes REAL,
    obs_manganes TEXT,
    boro REAL,
    obs_boro TEXT,
    sodio REAL,
    obs_sodio TEXT,
    cloro REAL,
    obs_cloro TEXT,
    relacao_ca_mg REAL,
    obs_relacao_ca_mg TEXT,
    relacao_ca_k REAL,
    obs_relacao_ca_k TEXT,
    relacao_mg_k REAL,
    obs_relacao_mg_k TEXT,
    sat_ca_ctc REAL,
    obs_sat_ca_ctc TEXT,
    sat_mg_ctc REAL,
    obs_sat_mg_ctc TEXT,
    sat_k_ctc REAL,
    obs_sat_k_ctc TEXT,
    indice_sat_na REAL,
    obs_indice_sat_na TEXT,
    soma_bases REAL,
    obs_soma_bases TEXT,
    ctc_efetiva REAL,
    obs_ctc_efetiva TEXT,
    ctc_ph7 REAL,
    obs_ctc_ph7 TEXT,
    sat_al REAL,
    obs_sat_al TEXT,
    sat_bases REAL,
    obs_sat_bases TEXT,
    tipo_aplicacao TEXT,
    saturacao_bases REAL,
    prnt REAL,
    necessidade_calagem TEXT,
    qtd_calcario REAL
);
''')

conexao.commit()
conexao.close()
